# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # prevnext: 文章末尾的上一页与下一页
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  enable: true
  author_photo: /images/avatar.png
  author_nickname: heycn's blog
  path: /

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 链接信息
link: 
  # name: 名称
  # icon: 图标，目前仅支持IconFont部分图标
  # path: 地址
  # target: 跳转方式
  -
    # 档案
    name: archives
    icon: bookmark
    path: /archives/
  -
    name: github
    icon: github
    path: https://github.com/heycn
    target: _blank
  # -
  #   name: email
  #   icon: envelope
  #   path: 
  -
    name: twitter
    icon: twitter
    path: https://twitter.com/heycn_112
  # -
  #   name: wechat
  #   icon: wechat
  #   path:

# 页脚信息
footer:
  -
    name:
    path:
  -
    name:
    path:

# 文章搜索
# TODO: 搜索功能暂未实现
search:
  enable: false
  placeholder:
