# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # prevnext: 文章末尾的上一页与下一页
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  enable: true
  photo: /images/avatar.png
  path: /

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 链接信息
link: 
  -
    name: Blog
    title: Blog
    icon:
    path: /archives
  -
    name: Projects
    title: Projects
    icon:
    path: https://github.com/heycn
  -
    name:
    title: GitHub
    icon: github
    path: https://github.com/heycn
    target: _blank
  -
    name:
    title: Twitter
    icon: twitter
    path: https://twitter.com/heycn_112

# 页脚信息
footer:
  -
    name:
    path:
  -
    name:
    path:

# 文章搜索
# TODO: 搜索功能暂未实现
search:
  enable: false
  placeholder:
